Bring aaa.asp into existence
Benricheson101/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa pull request #91
Opened 2020-10-05 02:15 UTC by aboutDavid

2020-10-05 02:43 UTC, Benricheson101 commented
is it possible to make it add one `a` at a certain interval? similarly to how aaa.html works https://github.com/Benricheson101/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/blob/af2548f0cfade9eae04e50cd0a3bb8e1cb3f16f2/aaa.html#L5

2020-10-05 03:19 UTC, aboutDavid commented
I'm not really sure. I barely write anything in ASP

I can look it up

2020-10-05 11:31 UTC, RiversideRocks commented
Probably not because ASP is server side (Active Server Pages)

2020-10-05 13:11 UTC, aboutDavid commented
Yeah, I could not find anything

2020-10-06 15:09 UTC, aboutDavid commented
Should I do this in Javascript also?

2021-04-21 18:47 UTC, democat3457 requested changes
asp has such a limited documentation... but this cleans up the code a bit and actually prints 'a' now

2021-04-21 18:47 UTC, democat3457 commented on aaa.asp
> +response.write("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
It'd probably be unwise to keep adding on to the title, might make the supposed browser crash?

2021-04-21 18:47 UTC, democat3457 commented on aaa.asp
> +%></h1><p><%
```suggestion
<p><%
```
It would be adding two per iteration and on separate lines rather than just one

2021-04-21 18:47 UTC, democat3457 commented on aaa.asp
> +response.write("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
```suggestion
Do Until False
  response.write("a")
Loop
```

This *should* work, I'm not sure if it'll print on new lines?

2022-07-23 01:51 UTC, closed without merging